//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class booksEntities : DbContext
    {
        public booksEntities()
            : base("name=booksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMIN { get; set; }
        public virtual DbSet<NHA_XUAT_BAN> NHA_XUAT_BAN { get; set; }
        public virtual DbSet<SACH> SACH { get; set; }
        public virtual DbSet<TAC_GIA> TAC_GIA { get; set; }
        public virtual DbSet<THE_LOAI> THE_LOAI { get; set; }
        public virtual DbSet<Y_KIEN> Y_KIEN { get; set; }
    
        public virtual ObjectResult<string> SP_GetBookDetail(Nullable<int> mASACH)
        {
            var mASACHParameter = mASACH.HasValue ?
                new ObjectParameter("MASACH", mASACH) :
                new ObjectParameter("MASACH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GetBookDetail", mASACHParameter);
        }
    }
}
