//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRONG_SO
    {
        public string ID { get; set; }
        public long EID { get; set; }
        public int TRONG_SO1 { get; set; }
    
        public virtual DAC_TRUNG_CAM_XUC DAC_TRUNG_CAM_XUC { get; set; }
        public virtual DAC_TRUNG_NGU_NGHIA DAC_TRUNG_NGU_NGHIA { get; set; }
    }
}
