//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Y_KIEN
    {
        public int MA_SACH { get; set; }
        public int MA_Y_KIEN { get; set; }
        public string NOI_DUNG { get; set; }
        public string DANH_GIA { get; set; }
        public System.DateTime NGAY { get; set; }
    
        public virtual SACH SACH { get; set; }
    }
}
